title: Portfolio Tammy Hartline # your name (or website title) here
layout: _layouts/default.html
logo: "https://media.licdn.com/dms/image/D5603AQGil6vwByqc7g/profile-displayphoto-shrink_800_800/0/1695260208506?e=1721260800&v=beta&t=txt3Nl4Dbmil-2qhUp0Rv0HeATRYXOunV1W4QPhnjx8" # your photo (or logo) here
description: > 

Social: >
  <a href="https://www.linkedin.com/in/tammy-hartline-91981266/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
